import ContactsMenu from './components/contacts-menu/contactsMenu';
import Maincontent from './components/main-content/maincontent';
import Sidemenu from './components/side-menu/Sidemenu';
import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Sidemenu />
        <ContactsMenu />
        <Maincontent>
          {children}
        </Maincontent>
      </body>
    </html>
  );
}
