import { Inter } from 'next/font/google';
import Maincontent from './components/main-content/MainContent';
import SecondRow from './components/second-row/SecondRow';
import Sidemenu from './components/side-menu/SideMenu';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <Sidemenu />
        <SecondRow content={{ type: "message" }} />
        <Maincontent>
          {children}
        </Maincontent>
      </body>
    </html>
  );
}
